<?php if($this->getRequest()->getActionName() == 'index'): ?>
<div id="messages-note"><ul class="messages note"><li class="notice-msg"><ul><li><?php echo $this->__('Clicks & Impressions of a Banner in each Slider') ?></li></ul></li></ul></div>
<?php else: ?>
<div id="messages-note"><ul class="messages note"><li class="notice-msg"><ul><li><?php echo $this->__('Clicks & Impressions of a Banner in all Sliders') ?></li></ul></li></ul></div>
<?php endif; ?>
<div class="magestore-bannerslider-report" style="float:right; margin-bottom: -20px;">
	<span style="float: left; margin-right:20px;"><h3 class="icon-head" style="color:#eb5e00;margin-bottom:0px;"><?php echo $this->__('Choose date to report');?></h3></span>
	<div class="f-left">
            <div id="magestore-bannerslider-formdate"><?php echo $this->__('From') ?>:&nbsp;<input class="input-text no-changes required-entry" type="text" id="period_date_from" name="report_from" value="<?php echo $this->getFilter('report_from') ?>" style="width:5em" /> <img src="<?php echo $this->getSkinUrl('images/grid-cal.gif') ?>" title="<?php echo $this->__('Select Date') ?>" id="period_date_from_trig" alt="<?php echo $this->__('Select Date') ?>" class="v-middle"/>&nbsp;&nbsp;</div>
			<div id="period_date_from_advaice"></div>
		</div>
	<div class="f-left">
		<div id="magestore-bannerslider-todate"><?php echo $this->__('To') ?>:&nbsp;<input  class="input-text no-changes required-entry" type="text" id="period_date_to" name="report_to"  value="<?php echo $this->getFilter('report_to') ?>" style="width:5em" /> <img src="<?php echo $this->getSkinUrl('images/grid-cal.gif') ?>" class="v-middle" title="<?php echo $this->__('Select Date') ?>"id="period_date_to_trig" alt="<?php echo $this->__('Select Date') ?>"/>&nbsp;&nbsp;</div>
			<div id="period_date_to_advaice"></div>
	</div>	
</div>
<script type="text/javascript">
//<![CDATA[
	Calendar.setup({
		inputField : 'period_date_from',
        ifFormat : '<?php echo $this->getDateFormat() ?>',
        button : 'period_date_from_trig',
        align : 'Bl',
        singleClick : true
        });
        Calendar.setup({
        inputField : 'period_date_to',
        ifFormat : '<?php echo $this->getDateFormat() ?>',
        button : 'period_date_to_trig',
        align : 'Bl',
        singleClick : true
	});
//]]>
</script>